name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd rust/difbuilder && cargo build --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: matrix.os == 'macos-latest'
      with:
        name: DifBuilderLib-${{ matrix.os }}
        path: |
          ${{github.workspace}}/rust/difbuilder/target/release/libdifbuilder.dylib
          
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        name: DifBuilderLib-${{ matrix.os }}
        path: |
          ${{github.workspace}}/rust/difbuilder/target/release/libdifbuilder.so

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      if: matrix.os == 'windows-latest'
      with:
        name: DifBuilderLib-${{ matrix.os }}
        path: |
          ${{github.workspace}}/rust/difbuilder/target/release/difbuilder.dll
